<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-24M7K4D" failures="0" tests="2" name="com.bhim.npci.endtoend.HomeTest" time="0.001" errors="1" timestamp="2023-07-14T12:25:13 IST" skipped="1">
  <testcase classname="com.bhim.npci.endtoend.HomeTest" name="config_BC" time="0.000">
    <error message="Cannot invoke &quot;com.bhim.npci.genericutility.FileUtility.readDataFromPropertyFile(String)&quot; because &quot;this.fileUtils&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.bhim.npci.genericutility.FileUtility.readDataFromPropertyFile(String)" because "this.fileUtils" is null
at com.bhim.npci.genericutility.BaseClass.config_BC(BaseClass.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- config_BC -->
  <testcase classname="com.bhim.npci.endtoend.HomeTest" name="checkingBalanceAndVerifyTest" time="0.001">
    <skipped/>
    <system-out>
      <![CDATA[checkingBalanceAndVerifyTest----------EXECUTION SKIPPED]]>
    </system-out>
  </testcase> <!-- checkingBalanceAndVerifyTest -->
  <system-out>
    <![CDATA[enteringWrongPinWhileSendingMoneyTest--------TEST SCRIPT EXECUTION STARTED
enteringWrongPinWhileSendingMoneyTest--------EXECUTED SUCCESSFULLY
payThroughScanner--------TEST SCRIPT EXECUTION STARTED
payThroughScanner--------EXECUTED SUCCESSFULLY
sendInvalidAmountTest--------TEST SCRIPT EXECUTION STARTED
sendInvalidAmountTest--------EXECUTED SUCCESSFULLY
sendingMoneyToContactAndValidateBalanceTest--------TEST SCRIPT EXECUTION STARTED
sendingMoneyToContactAndValidateBalanceTest--------EXECUTED SUCCESSFULLY
checkingBalanceAndVerifyTest--------TEST SCRIPT EXECUTION STARTED
checkingBalanceAndVerifyTest----------EXECUTION SKIPPED
verifyLanguageTest--------TEST SCRIPT EXECUTION STARTED
verifyLanguageTest----------EXECUTION SKIPPED
sendFeedback--------TEST SCRIPT EXECUTION STARTED
sendFeedback----------EXECUTION SKIPPED]]>
  </system-out>
</testsuite> <!-- com.bhim.npci.endtoend.HomeTest -->
